In [1]:
pip install numpy


     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------------------------- ------------ 41.0/61.0 kB 667.8 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 819.4 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB 1.3 MB/s eta 0:00:13
   ---------------------------------------- 0.1/15.8 MB 1.6 MB/s eta 0:00:10
    --------------------------------------- 0.3/15.8 MB 2.0 MB/s eta 0:00:08
   - -------------------------------------- 0.4/15.8 MB 2.4 MB/s eta 0:00:07
   - -------------------------------------- 0.6/15.8 MB 2.8 MB/s eta 0:00:06
   - -------------------------------------- 0.8/15.8 MB 2.8 MB/s eta 0:00:06
   -- ------------------------------------- 0.9/15.8 MB 3.0 MB/s eta 0:00:05
   -- ------------------------------------- 1.1/15.8 MB 3.0 MB/s eta 0:00:05
   --- ------------------------------------ 1.3/15.8 MB 3.0 MB/s eta 0:00:05
   --

ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python310\\Scripts\\f2py.exe' -> 'C:\\Python310\\Scripts\\f2py.exe.deleteme'


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np


In [5]:
arr=np.random.randint(1,10 , size=(3,3))

In [6]:
arr

array([[4, 6, 6],
       [5, 5, 1],
       [6, 1, 9]])

In [7]:
np.size(arr)

2

In [8]:
arr.dtype

dtype('int32')

In [9]:
np.ndim(arr)

2

In [14]:
do_arr = np.random.randint(10,100,size=(2,5))

In [15]:
do_arr

array([[48, 63, 14, 77, 57],
       [76, 28, 26, 84, 75]])

In [16]:
do_arr.shape

(2, 5)

In [17]:
arr_r = np.random.randint(1,50,size=(10))

In [18]:
arr_r

array([33, 38, 10, 35, 18, 38,  3, 23, 42, 24])

In [19]:
np.mean(arr_r)

26.4

In [25]:
a = np.random.randint(1,50,size=(1,2))

In [26]:
b = np.random.randint(1,50,size=(1,2))

In [27]:
a

array([[46, 36]])

In [28]:
b

array([[ 8, 17]])

In [29]:
a+b

array([[54, 53]])

In [30]:
list = np.random.randint(1,100,size=(20))

In [31]:
list

array([48, 89, 69,  1,  3, 77, 91, 50, 16, 42, 83, 20, 46,  8, 95, 23, 95,
       28, 43, 38])

In [38]:
list_l = list[list>50]

In [39]:
list_l

array([89, 69, 77, 91, 83, 95, 95])

In [43]:
l = np.random.randint(1,10,size=(10))

In [44]:
l

array([9, 5, 5, 7, 1, 6, 2, 3, 8, 8])

In [46]:
np.random.shuffle(l)

In [47]:
l

array([1, 2, 8, 5, 7, 9, 8, 3, 5, 6])